### ISSUE TITLE
Dataset access

### ISSUE THREAD

**Issue by j-min** [ztyang23/BACON#1]
Hi, thanks for releasing the code/data!

I'd like to check the dataset as mentioned here - https://github.com/ztyang23/BACON?tab=readme-ov-file#dataset,
but it seems like that we need a permission to access the below link
https://drive.google.com/file/d/1sSBTxkRsyL_bk0XfrXOIdGpTY2XzA_bK/view?usp=drive_link

Would you please make the link publicly available? Thanks!

**Comment by ztyang23** [comment]
Thank you for your interest in our work! You can download our training data via this [link](https://huggingface.co/datasets/ztyang196/BACON_dataset) (We have also updated the corresponding section in the README). Additionally, we have made annotations.zip and results.zip available for download.
